name: "Documentation (Reusable)"

on:
  pull_request:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"
    paths:
      - "doc/**"
      - ".github/workflows/docs.yaml"
      - "README.md"
  push:
    branches:
      - "[0-9]+.[0-9]+"
      - "[0-9]+.x"
      - "*_actions"
    paths:
      - "doc/**"
      - ".github/workflows/docs.yaml"
      - "README.md"

permissions:
  contents: read

jobs:
  docs:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-docs.yaml@main
    with:
      docs_path: "doc"
